a = int(input("a = "))
b = int(input("b = "))
c = int(input("c = "))
x = int(input("x = "))
y = int(input("y = "))

print("\n1. x >-2 and x <= 100: ", x >-2 and x <= 100)
print("2. 1>x>=-10, x#0: ", 1>x>=-10 and x!=0)
print("3. -5<x=<0: ", -5<x<=0)
print("4. x>=10 и x<a: ", x>=10 and x<a)
print("5. a<=x<=0: ", a<=x<=0)
print("6. a<x<b: ", a<x<b)
print("7. a>y>b: ", a>y>b)
print("8. a<=y<=b, y#c a<c< b: ", a<=y<=b and y!=c and a<c<b)